### ISSUE TITLE
Install Playbook fails when there is no default route on host

### ISSUE THREAD

**Issue by godelc7** [CNES/openbach#3]
In my environment, none of the machine have a default route, which lead to the following error during installation:

`fatal: [192.168.21.21]: FAILED! => 
  msg: |-
    The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'address'
  
    The error appears to be in '/home/user/openbach_stuffs/openbach/ansible/install.yml': line 72, column 7, but may
    be elsewhere in the file depending on the exact syntax problem.
  
    The offending line appears to be:
  
      pre_tasks:
        - name: Configure Default OpenBACH Name
          ^ here`

A good explanation for this error is given here: https://medium.com/opsops/ansible-default-ipv4-is-not-what-you-think-edb8ab154b10

A fix that worked for me is the following: in `ansible/install.yml` line 73 rather use `ansible_eth0.ipv4.address` instead of `ansible_default_ipv4.address`.

Is this a viable solution?

**Comment by Kniyl** [comment]
Hi,

Thank you for the link. I’d rather use the solution presented there (`ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0])`) rather than hardcoding the name of an interface (`eth0`) that is much more likely to **not** be on the machine.

On the other hand, this variable is only used if you do not provide a custom name to your machines. So specifying an inventory like:
```
[controller]
192.168.1.100 openbach_name=Controller

[agent]
192.168.1.101 openbach_name=Client
192.168.1.102 openbach_name=Server
```
should get you going as well.

**Comment by godelc7** [comment]
Thanks for reply,

>I’d rather use the solution presented there (`ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0])`) rather than hardcoding the name of an interface (`eth0`) that is much more likely to not be on the machine.

Sounds good. I haven't try that, but I will do it and let you know.

> On the other hand, this variable is only used if you do not provide a custom name to your machines.

I have provided all `openbach_name` in my inventory file. But still, the playbook failed. My guess is that the playbook instructions are first interpreted or translated or somehow compiled before their actual execution. And it is this first step (translation/compilation) that failed.

**Comment by Kniyl** [comment]
> I have provided all `openbach_name` in my inventory file. But still, the playbook failed. My guess is that the playbook instructions are first interpreted or translated or somehow compiled before their actual execution. And it is this first step (translation/compilation) that failed.

Thanks for that bit, it will save me on testing that hypothesis. You can safely remove the task / the `default` clause if you provided a name for all your machines. I will provide a fix in the next release.

**Comment by godelc7** [comment]
Hi,

>I’d rather use the solution presented there `(ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0]))` rather than hardcoding the name of an interface (eth0) that is much more likely to not be on the machine.

can you share the entire line 73 of `ansible/install.yml` how it should like? Because I tried many different syntaxes all involving `ansible_default_ipv4.address`. But none of those work. The only thing that worked for me is to completely remove `ansible_default_ipv4.address` out of the instruction. Here is the complete line 73 as it worked for me:

`set_fact: openbach_name={{ openbach_name | default(ansible_hostname + ' ' + ansible_all_ipv4_addresses[0]) }}`

**Comment by Kniyl** [comment]
I ended up using a similar approach with a fallback "just in case": https://github.com/CNES/openbach/blob/dev/ansible/install.yml#L73
